window.__adroll||(function(){function g(){this.version="1.0";this.exp=8760;this.eexp=720;this.pv=1E11*Math.random();this.__adc="__ar_v4";this._nad=0;this._lce=null;this._loaded=this._broken=!1;this._url=2E3;this._kwl=300;this._r={};this.cm_urls=[];this._logs=[];this.consent_networks={facebook:"f",linkedin:"linkedin"};this.pixelstart=this.session_time=0;this._init_floc_trial();for(var a=Array(4),b=0;b<a.length;b++)a[b]=(Math.round(1E11*Math.random()).toString(16)+Array(9).join("0")).substr(0,8);this._set_global("adroll_sid",a.join(""));
this._has_global("adroll_adv_id")&&(this.load_experiment_js(),this.init_pixchk(),this._load_precheck_js(),this.trigger_gtm_consent_event(),this.load_pixel_assistant(),["adroll_adv_id","adroll_pix_id"].forEach(function(a){window.hasOwnProperty(a)&&("string"===typeof window[a]||window[a]instanceof String)&&(window[a]=window[a].replace(/[^A-Z0-9_]/g,""))}));this.is_under_experiment("pixel_timing")&&this._pixel_timing(!0,!0,null)};g.prototype.call_consent_check=function(){function a(){var a=["_s="+b.get_adroll_sid(),"_b=2"];"#_ar_gdpr="===window.location.hash.substr(0,10)&&a.push("dbg="+unescape(window.location.hash.substr(10)));window.adroll_fpconsent&&a.push("_afc=1");a=b._srv("/consent/check/"+b._global("adroll_adv_id")+"?"+a.join("&"));b.add_script_element(a)}var b=this;this._is_defined(window.adroll_fpconsent)?a():window.setTimeout(a,100)};
g.prototype.call_consent_write=function(a){window.adroll_fpconsent&&(a+="&_afc=1");this.add_script_element(this._srv("/consent/write?"+a))};g.prototype._consent_cookie=function(a){return a?(this.set("__adroll_consent",a,8760),a):this.get("__adroll_consent")};g.prototype.load_consent_banner=function(){window.document.getElementById("__adroll_consent_banner_el")||this.add_script_element("s.adroll.com/j/consent_tcfv2.js",{id:"__adroll_consent_banner_el"})};g.prototype.get_consent_params=function(){return this.get("__adroll_consent_params")};
g.prototype.set_consent_params=function(a){this.set("__adroll_consent_params",a)};g.prototype.clear_consent_params=function(){this.del("__adroll_consent_params")};g.prototype.handle_null_consent=function(a){a||(a=this.get_consent_params())&&this.call_consent_write(a)};g.prototype.save_first_party_consent=function(a){var b=(a||{}).euconsent;if((a=(a||{}).arconsent)||b)this._consent_cookie(a),window.localStorage.setItem("__adroll_consent_data",this.jsonStringify({arconsent:a,euconsent:b}))};
g.prototype.get_first_party_consent=function(){if(this._has_global("__adroll_consent_data"))return this._global("__adroll_consent_data");var a=null;try{if(window.localStorage){var b=window.localStorage.getItem("__adroll_consent_data");b&&(a=this.jsonParse(b))}}catch(c){}if(b=this._consent_cookie())a=a||{},a.arconsent=b;this._set_global("__adroll_consent_data",a);return a};
g.prototype.trigger_gtm_consent_event=function(a){function b(a,b,c){b=isNaN(Number(b))?"c:"+b:"tcf:"+b;!0!==c&&!1!==c&&(c="unknown");a[c][b]=1}function c(a){return","+r.object_keys(a).join(",")+","}if(!window.dataLayer||"function"===typeof window.dataLayer.push)if(window.dataLayer=window.dataLayer||[],a){var d=this._global("__adroll_consent"),e=this._global("__adroll_consent_data")||{},f=e.eucookie||{},m=f.max_vendor_id||e.max_vendor_id||0,p=e.networks||[],l=f.purposes_allowed||0,h={"true":{},"false":{},
unknown:{}},k={"true":{},"false":{},unknown:{}},n={"true":{},"false":{}},r=this,q;if("boolean"===typeof d){for(q=0;q<p.length;q++)b(h,p[q],d);for(q=1;q<m;q++)b(h,q,d),b(k,q,d);for(q=1;25>q;q++)n[d][q]=1}else{for(q in d)d.hasOwnProperty(q)&&b(h,q,d[q]);for(q=1;q<=m;q++)b(k,q,(f.vendor_consent||{})[q]);for(q=0;24>q;q++)n[!!(l&1<<q)][q+1]=1}window.dataLayer.push({event:a,nextrollVendorsConsent:c(h["true"]),nextrollVendorsConsentUnknown:c(h.unknown),nextrollVendorsConsentDenied:c(h["false"]),nextrollVendorsRawConsent:c(k["true"]),
nextrollVendorsRawConsentUnknown:c(k.unknown),nextrollVendorsRawConsentDenied:c(k["false"]),nextrollPurposesConsent:c(n["true"]),nextrollPurposesConsentUnknown:null,nextrollPurposesConsentDenied:c(n["false"]),nextrollgdpr:this._global("__adroll_consent_is_gdpr"),nextrolliab:e.euconsent})}else window.dataLayer.push({event:"nextroll-ready"})};
g.prototype.set_consent=function(a,b,c,d,e,f){if(0===arguments.length){if(!this._has_global("__adroll_consent"))return;a=this._global("__adroll_consent")}var m="nextroll-consent";this._has_global("__adroll_consent")&&(m="nextroll-consent-modified");this._set_global("__adroll_consent",a);this._set_global("__adroll_consent_is_gdpr",c);this._set_global("__adroll_consent_data",f||{});d&&this._set_global("__adroll_consent_user_country",d);e&&this._set_global("__adroll_consent_adv_country",e);c&&("adroll"===
(f||{}).banner||b)&&this.load_consent_banner();if(this._install_cmp)this._install_cmp();else{var p=this;window.setTimeout(function(){p._install_cmp&&p._install_cmp()},1E3)}null===a?this.handle_null_consent(b):(this.save_first_party_consent(f),b||this.clear_consent_params(),this._trigger_consent_event&&this._trigger_consent_event(),!1!==a&&!1!==(a||{}).a&&(this._log_floc_cohort(),this._log_xavier_cluster(),this.set_first_party_cookie(),this.trigger_gtm_consent_event(m),this.call_next_tpc()))};
g.prototype._load_precheck_js=function(){this.add_script_element("https://s.adroll.com/j/pre/"+window.adroll_adv_id+"/"+window.adroll_pix_id+"/fpconsent.js");this.add_script_element("https://s.adroll.com/j/pre/"+window.adroll_adv_id+"/"+window.adroll_pix_id+"/index.js")};g.prototype.cookieEnabled=function(a){if(this._global("adroll_ext_network")||this._global("adroll_optout")||this._broken)return!1;if(2<=this._nad||a)return this._lce;this.set("_te_","1");return"1"===this.get("_te_")?(this.del("_te_"),0<this._nad&&!this.get(this.__adc)?this._lce=!1:this._lce=!0):this._lce=!1};
g.prototype.get=function(a){var b=window.document.cookie;if(null===b)return this._broken=!0,null;var c;0>b.indexOf(a+"=")?b=null:(a=b.indexOf(a+"=")+a.length+1,c=b.indexOf(";",a),-1===c&&(c=b.length),b=b.substring(a,c),b=""===b?null:window.unescape(b));return b};
g.prototype.set=function(a,b,c){var d;c&&"number"===typeof c?(d=new Date,d.setTime(d.getTime()+36E5*c),c=d.toGMTString(),c="; expires="+c):c="";d="; domain="+window.location.hostname;b=window.escape(b);window.document.cookie=a+"="+b+c+"; path=/"+d+"; samesite=lax"};g.prototype.del=function(a){this.set(a,"",-8760)};
g.prototype.check_cookie=function(a,b){if(this._global("adroll_ext_network")||this._global("adroll_optout"))return"";for(var c=a.split("|"),d=c.length-1;0<=d;d--)if(c[d]){var e=c[d].split(":");b===e[0]&&(e[2]=""+(parseInt(e[2])+1),c[d]=e.join(":"))}return c.join("|")};g.prototype.handle=function(a){var b=this.get(this.__adc)||"";-1!==b.indexOf(a)?this.set(this.__adc,this.check_cookie(b,a),this.exp):(a=[b,[a,this.get_date(this.eexp),"1"].join(":")].join("|"),this.set(this.__adc,a,this.exp))};
g.prototype.expire_old=function(){if(!this._global("adroll_ext_network")&&!this._global("adroll_optout")){for(var a=this.get_date(!1),b=this.get(this.__adc),b=b?b.split("|"):[""],c=[],d=b.length-1;0<=d;d--)b[d]&&b[d].split(":")[1]>a&&c.push(b[d]);this.set(this.__adc,c.join("|"),this.exp)}};g.prototype.get_date=function(a){var b=new Date;a&&b.setTime(b.getTime()+36E5*a);a=""+b.getUTCFullYear();var c=b.getUTCMonth(),c=10<=c?c:"0"+c,b=b.getUTCDate();return[a,c,10<=b?b:"0"+b].join("")};
g.prototype.consent_allowed=function(a){var b=this._global("__adroll_consent");return"object"===typeof b?b[a]:b};g.prototype.generate_link=function(){return""};g.prototype.view=function(a){var b=new window.Image;b.src=this._srv("/view/"+a);b.setAttribute("width","1");b.setAttribute("height","1");b.setAttribute("border","0");b.setAttribute("alt","");this._head().appendChild(b)};g.prototype.set_cookie=function(){};
g.prototype.reset=function(){this._set_global("adroll_c_id",null);this._set_global("adroll_url_macro","");this._set_global("adroll_c_macro","");this._set_global("adroll_cpm_macro","");this._set_global("adroll_ext_network",null);this._set_global("adroll_subnetwork",null);this._set_global("adroll_ad_payload",null);this._set_global("adroll_win_notif",null)};g.prototype.set_pixel_cookie=function(a,b,c){this._global("adroll_optout")||(this.handle(a),this.handle(b),this.handle(c),this.pixel_loaded())};
g.prototype.add_pixel_load_callback=function(a){this._loaded?a():this._ensure_global("adroll_callbacks",[]).push(a)};g.prototype.pixel_loaded=function(){this._loaded=!0;for(var a=this._ensure_global("adroll_callbacks",[]),b=0;b<a.length;b++)a[b].called||(a[b](),a[b].called=!0)};g.prototype.addLoadEvent=function(a){if(this._has_global("__adroll_loaded")&&this._global("__adroll_loaded")||this._has_global("_adroll_ie")&&this._global("_adroll_ie")||/msie/i.test(window.navigator.userAgent))return a();if(/WebKit/i.test(window.navigator.userAgent)){var b=window.setInterval(function(){/loaded|complete/.test(window.document.readyState)&&window.clearInterval(b);a()},10);return null}var c=window.onload;window.onload=function(){a();c&&c()}};
g.prototype._head=function(){return(window.document.getElementsByTagName("head")||[null])[0]||(window.document.getElementsByTagName("body")||[null])[0]||window.document.getElementsByTagName("script")[0].parentNode};g.prototype.listenToEvent=function(a,b,c){a.addEventListener?a.addEventListener(b,this.wrapException(c),!1):a.attachEvent("on"+b,this.wrapException(c))};g.prototype.runCookieMatch=function(){var a=this.cm_urls.length;if(!(0>=a))for(var b=0;b<=a;b++)this.popAndSend()};
g.prototype.popAndSend=function(){if(!(0>=this.cm_urls.length)){var a=this.cm_urls.shift(),b=new Image;b.src=a;b.setAttribute("alt","")}};g.prototype.add_param_to_url=function(a,b){var c=a.indexOf("?"),d="",e="";-1!==c?(d=a.slice(0,c+1),e="&"+a.slice(c+1)):(c=a.indexOf("#",-1===c?0:c),-1===c?d=a+"?":(d=a.slice(0,c)+"?",e=a.slice(c)));return d+b+e};g.prototype.is_under_experiment=function(a){return window.adroll_exp_list&&0<=window.adroll_exp_list.indexOf(a)};g.prototype.load_experiment_js=function(){var a=window.document.getElementById("adroll_scr_exp");return a?a:this.add_script_element("https://s.adroll.com/j/exp/"+window.adroll_adv_id+"/index.js",{id:"adroll_scr_exp",onError:"window.adroll_exp_list = [];"})};g.prototype.is_experiment_js_loaded=function(){return!!window.adroll_exp_list};
g.prototype.is_test_advertisable=function(){return"ADV_EID"===this._global("adroll_adv_id")};g.prototype.if_under_experiment_js=function(a,b,c,d){var e=this;this.load_experiment_js();this.on_experiment_loaded(function(){e.is_under_experiment(a)?"function"===typeof b&&b.call(e):"function"===typeof c&&c.call(e)},d)};
g.prototype.on_experiment_loaded=function(a,b){function c(){if(e.is_experiment_js_loaded()||e.is_test_advertisable())d=!0;d?a.call(e):window.setTimeout(c,10)}var d=!1,e=this;window.setTimeout(function(){d=!0},b||500);c()};g.prototype.external_data_to_qs=function(a){var b=[],c=this.get_external_data();if(!c)return null;for(var d in c)c.hasOwnProperty(d)&&this._is_defined(c[d])&&null!==c[d]&&b.push(this.normalize_var(window.escape(""+d)+"="+window.escape(""+c[d]),!1));b=b.join("&");a&&(b=window.escape(b));return"adroll_external_data="+b};
g.prototype.replace_external_data=function(a){var b=this.get_external_data(),c=this.get_conversion_value(),d=null,e;if(b)for(e in b)b.hasOwnProperty(e)&&(d=new RegExp("\\["+e+"\\]","gi"),a=a.replace(d,b[e]),d=new RegExp("\\["+e+"_ESC\\]","gi"),a=a.replace(d,window.escape(b[e])));if(c)for(e in c)c.hasOwnProperty(e)&&(d=new RegExp("\\["+e+"\\]","gi"),a=a.replace(d,c[e]),d=new RegExp("\\["+e+"_ESC\\]","gi"),a=a.replace(d,window.escape(c[e])));return a};
g.prototype.get_external_data=function(){if(this._has_global("adroll_custom_data")){var a=this._global("adroll_custom_data"),b={},c;for(c in a)a.hasOwnProperty(c)&&"undefined"!==a[c]&&(b[c.toLowerCase()]=a[c]);return b}return null};
g.prototype.get_conversion_value=function(){var a=this._ensure_global("adroll_currency",null),b=this._ensure_global("adroll_conversion_value",null),c=this._ensure_global("adroll_conversion_value_in_dollars",null);return b?{conv_value:""+b,currency:a}:c?{conv_value:""+parseInt(100*c),currency:"USC"}:null};g.prototype._has_global=function(a){return this._is_defined(this._global(a))};g.prototype._global=function(a){return window[a]};g.prototype._set_global=function(a,b){window[a]=b};g.prototype._unset_global=function(a){delete window[a]};g.prototype._ensure_global=function(a,b){this._has_global(a)||this._set_global(a,b);return this._global(a)};g.prototype.jsonStringify=function(a){this.jsonStringifyFunc||this.initJsonStringify();return this.jsonStringifyFunc(a)};g.prototype.jsonParse=function(a){var b=this._global("JSON");return"function"===typeof b.parse?b.parse(a):eval("("+a+")")};
g.prototype.initJsonStringify=function(){var a=this._global("JSON");this.jsonStringifyFunc=a&&a.stringify&&"function"===typeof a.stringify?a.stringify:function(){function a(b){return e[b]||"\\u"+(b.charCodeAt(0)+65536).toString(16).substr(1)}var c=Object.prototype.toString,d=Array.isArray||function(a){return"[object Array]"===c.call(a)},e={'"':'\\"',"\\":"\\\\","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t"},f=/[\\"\u0000-\u001F\u2028\u2029]/g;return function p(e){if(null===e)return"null";
if("number"===typeof e)return isFinite(e)?e.toString():"null";if("boolean"===typeof e)return e.toString();if("object"===typeof e){if("function"===typeof e.toJSON)return p(e.toJSON());if(d(e)){for(var h="[",k=0;k<e.length;k++)h+=(k?", ":"")+p(e[k]);return h+"]"}if("[object Object]"===c.call(e)){h=[];for(k in e)e.hasOwnProperty(k)&&h.push(p(k)+": "+p(e[k]));return"{"+h.join(", ")+"}"}}return'"'+e.toString().replace(f,a)+'"'}}()};g.prototype.macro_values=function(){var a=this._ensure_global("adroll_cpm_macro",null),b=this._ensure_global("adroll_url_macro",null),c=this._ensure_global("adroll_c_macro",null),d=this._ensure_global("adroll_subnetwork",null),e=this._ensure_global("adroll_ad_payload",null),f=this._ensure_global("adroll_win_notif",null),m=this._ensure_global("adroll_rtb_dict",null),p=this._ensure_global("adroll_debug_string",null),l={r:/^\$\{.*\}$/i,g:/^%%.*%%$/i,b:/^\[.*\]$/i,x:/^\$\{.*\}$/i,t:/INSERTCLICKTRACKER/}[this._global("adroll_ext_network")],
l=this._is_defined(l)?l:/CANNOT_MATCH_THIS/,h={};a&&!l.test(a)&&(h.adroll_cpm_macro=a);p&&!l.test(p)&&(h.adroll_debug_string=p);b&&!l.test(b)&&(h.adroll_url_macro=b);c&&!l.test(c)&&(h.adroll_c_macro=c);d&&!l.test(d)&&(h.adroll_subnetwork=d);e&&!l.test(e)&&(h.adroll_ad_payload=e);f&&!/^[|$]/.test(f)&&(h.adroll_win_notif=f);if(m&&("string"!==typeof m||!/^[|$]/.test(m))){if("string"===typeof m)try{0===m.indexOf("b64:")&&(m=atob(m.substr(4))),m=this.jsonParse(m)}catch(k){this.log("failed to parse: "+
k),m={}}"object"===typeof m&&(h.adroll_rtb_dict=m)}return h};g.prototype.format_macros=function(a,b,c,d){a=this.macro_url_params(this.macro_values(),a,b,c,d);return this.maybe_apply_click_macro(a)};g.prototype.apply_exchange_macro=function(a,b){var c=this._global("adroll_cpm_macro"),d=window.unescape(c),c=new RegExp(c.replace(/[-\/\\^$*+?.()|[\]{}]/g,"\\$&"),"g");a=a.replace(c,d);return b+window.escape(a)};
g.prototype.maybe_apply_imp_macro=function(a){var b=this._global("adroll_imp_prefix_macro");return b?this.apply_exchange_macro(a,b):a};g.prototype.maybe_apply_click_macro=function(a){var b=this._global("adroll_click_prefix_macro");if(b){var c=this.parseUri(a);if(this.endswith(c.path,".re")||this.endswith(c.path,".dy")||this.endswith(c.path,".tp"))return this.apply_exchange_macro(a,b)}return a};
g.prototype.macro_url_params=function(a,b,c,d,e){e=this._is_defined(e)?e:!1;var f=d?window.escape:function(a){return a},m=a.adroll_cpm_macro,p=a.adroll_url_macro,l=c?a.adroll_c_macro:null,h=[],k=this.is_lenient_click(b);!k&&e&&h.push(["desturl",""]);l&&0===l.indexOf("http")?(e=f,"g"===this._global("adroll_ext_network")&&(e=d?function(a){return a}:window.unescape),h.push(["clickurl",e(l)])):k&&e&&h.push(["clickurl",""]);this._global("adroll_ext_network")&&h.push(["adroll_network",this._global("adroll_ext_network")]);
m&&h.push(["cpm",m]);a.adroll_subnetwork&&h.push(["adroll_subnetwork",a.adroll_subnetwork]);a.adroll_ad_payload&&h.push(["adroll_ad_payload",a.adroll_ad_payload]);a.adroll_debug_string&&h.push(["debug_string",f(a.adroll_debug_string)]);p&&(a=this.parseUri(window.unescape(p)),h.push(["site_url",f("http://"+a.host)]),c&&(h.push(["adroll_width",f(this._global("adroll_width"))]),h.push(["adroll_height",f(this._global("adroll_height"))])));this.log("Macros found "+this.serialize(h));return b?this.buildurl(b,
h):this.serialize(h)};g.prototype.serialize=function(a){if(a.length){for(var b=[],c=a.length-1;0<=c;c--)b.push(a[c].join("="));return b.join("&")}return""};g.prototype.includes=function(a,b){return-1!==a.indexOf(b)};g.prototype.startswith=function(a,b){return 0===a.indexOf(b)};g.prototype.endswith=function(a,b){return-1!==a.indexOf(b,a.length-b.length)};
g.prototype.buildurl=function(a,b){var c=this.serialize(b),d=a.indexOf("?");return c?d===a.length-1?a+c:-1!==d?"&"===a[a.length-1]?a+c:a+"&"+c:a+"?"+c:a};g.prototype.md5=function(){function a(a,b){var c=(a&65535)+(b&65535);return(a>>16)+(b>>16)+(c>>16)<<16|c&65535}function b(b,c,d,e,n,m){c=a(a(c,b),a(e,m));return a(c<<n|c>>>32-n,d)}function c(a,c,d,e,n,m,f){return b(c&d|~c&e,a,c,n,m,f)}function d(a,c,d,e,n,m,f){return b(c&e|d&~e,a,c,n,m,f)}function e(a,c,d,e,n,m,f){return b(d^(c|~e),a,c,n,m,f)}function f(m,l){var h=m[0],k=m[1],n=m[2],f=m[3],h=c(h,k,n,f,l[0],7,-680876936),f=c(f,h,k,n,l[1],12,-389564586),n=c(n,f,h,k,l[2],17,606105819),k=c(k,n,f,h,l[3],
22,-1044525330),h=c(h,k,n,f,l[4],7,-176418897),f=c(f,h,k,n,l[5],12,1200080426),n=c(n,f,h,k,l[6],17,-1473231341),k=c(k,n,f,h,l[7],22,-45705983),h=c(h,k,n,f,l[8],7,1770035416),f=c(f,h,k,n,l[9],12,-1958414417),n=c(n,f,h,k,l[10],17,-42063),k=c(k,n,f,h,l[11],22,-1990404162),h=c(h,k,n,f,l[12],7,1804603682),f=c(f,h,k,n,l[13],12,-40341101),n=c(n,f,h,k,l[14],17,-1502002290),k=c(k,n,f,h,l[15],22,1236535329),h=d(h,k,n,f,l[1],5,-165796510),f=d(f,h,k,n,l[6],9,-1069501632),n=d(n,f,h,k,l[11],14,643717713),k=d(k,
n,f,h,l[0],20,-373897302),h=d(h,k,n,f,l[5],5,-701558691),f=d(f,h,k,n,l[10],9,38016083),n=d(n,f,h,k,l[15],14,-660478335),k=d(k,n,f,h,l[4],20,-405537848),h=d(h,k,n,f,l[9],5,568446438),f=d(f,h,k,n,l[14],9,-1019803690),n=d(n,f,h,k,l[3],14,-187363961),k=d(k,n,f,h,l[8],20,1163531501),h=d(h,k,n,f,l[13],5,-1444681467),f=d(f,h,k,n,l[2],9,-51403784),n=d(n,f,h,k,l[7],14,1735328473),k=d(k,n,f,h,l[12],20,-1926607734),h=b(k^n^f,h,k,l[5],4,-378558),f=b(h^k^n,f,h,l[8],11,-2022574463),n=b(f^h^k,n,f,l[11],16,1839030562),
k=b(n^f^h,k,n,l[14],23,-35309556),h=b(k^n^f,h,k,l[1],4,-1530992060),f=b(h^k^n,f,h,l[4],11,1272893353),n=b(f^h^k,n,f,l[7],16,-155497632),k=b(n^f^h,k,n,l[10],23,-1094730640),h=b(k^n^f,h,k,l[13],4,681279174),f=b(h^k^n,f,h,l[0],11,-358537222),n=b(f^h^k,n,f,l[3],16,-722521979),k=b(n^f^h,k,n,l[6],23,76029189),h=b(k^n^f,h,k,l[9],4,-640364487),f=b(h^k^n,f,h,l[12],11,-421815835),n=b(f^h^k,n,f,l[15],16,530742520),k=b(n^f^h,k,n,l[2],23,-995338651),h=e(h,k,n,f,l[0],6,-198630844),f=e(f,h,k,n,l[7],10,1126891415),
n=e(n,f,h,k,l[14],15,-1416354905),k=e(k,n,f,h,l[5],21,-57434055),h=e(h,k,n,f,l[12],6,1700485571),f=e(f,h,k,n,l[3],10,-1894986606),n=e(n,f,h,k,l[10],15,-1051523),k=e(k,n,f,h,l[1],21,-2054922799),h=e(h,k,n,f,l[8],6,1873313359),f=e(f,h,k,n,l[15],10,-30611744),n=e(n,f,h,k,l[6],15,-1560198380),k=e(k,n,f,h,l[13],21,1309151649),h=e(h,k,n,f,l[4],6,-145523070),f=e(f,h,k,n,l[11],10,-1120210379),n=e(n,f,h,k,l[2],15,718787259),k=e(k,n,f,h,l[9],21,-343485551);m[0]=a(h,m[0]);m[1]=a(k,m[1]);m[2]=a(n,m[2]);m[3]=
a(f,m[3])}var m="0123456789abcdef".split("");return function(a){var b=a;/[\x80-\xFF]/.test(b)&&(b=unescape(encodeURI(b)));var c=b.length;a=[1732584193,-271733879,-1732584194,271733878];var d;for(d=64;d<=b.length;d+=64){for(var e=b.substring(d-64,d),r=[],q=void 0,q=0;64>q;q+=4)r[q>>2]=e.charCodeAt(q)+(e.charCodeAt(q+1)<<8)+(e.charCodeAt(q+2)<<16)+(e.charCodeAt(q+3)<<24);f(a,r)}b=b.substring(d-64);e=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];for(d=0;d<b.length;d++)e[d>>2]|=b.charCodeAt(d)<<(d%4<<3);e[d>>2]|=
128<<(d%4<<3);if(55<d)for(f(a,e),d=0;16>d;d++)e[d]=0;e[14]=8*c;f(a,e);for(b=0;b<a.length;b++){c=a;d=b;e=a[b];r="";for(q=0;4>q;q++)r+=m[e>>8*q+4&15]+m[e>>8*q&15];c[d]=r}return a.join("")}}();g.prototype._init_floc_trial=function(){var a=window.document.createElement("meta");a.httpEquiv="origin-trial";a.content="A41wt2Lsq30A9Ox/WehogvJckPI4aY9RoSxhb8FMtVnqaUle1AtI6Yf7Wk+7+Wm0AfDDOkMX+Wn6wnDpBWYgWwYAAAB8eyJvcmlnaW4iOiJodHRwczovL2Fkcm9sbC5jb206NDQzIiwiZmVhdHVyZSI6IkludGVyZXN0Q29ob3J0QVBJIiwiZXhwaXJ5IjoxNjI2MjIwNzk5LCJpc1N1YmRvbWFpbiI6dHJ1ZSwiaXNUaGlyZFBhcnR5Ijp0cnVlfQ==";this._head().appendChild(a)};
g.prototype._log_floc_cohort=function(){var a=this._global("adroll_seg_eid")||"";if("function"===typeof window.document.interestCohort){var b=this;window.document.interestCohort().then(function(c){if(c){var d=c.id;c=c.version;d&&c&&b._log_pex_event("floc",d,c,{seg:a},null)}})["catch"](function(a){b.log("floc-error:"+a)})}};
g.prototype._log_xavier_cluster=function(){function a(){window.RetrieveClusterID?window.RetrieveClusterID(function(a){c._log_pex_event("xidctx",a,"")}):window.setTimeout(function(){a()},10)}var b=this._ctx_filter();if(!window.document.getElementsByTagName("html")[0].innerHTML.match(b)){var c=this;"ADV_EID"!==this._ensure_global("adroll_adv_id","")&&(c.add_script_element("https://s.dca0.com/ctx.v1.1.min.js?1635953272"),a())}};
g.prototype._log_pex_event=function(a,b,c,d,e){a=encodeURIComponent(a);b=encodeURIComponent(b);c=encodeURIComponent(c);var f=this._ensure_global("adroll_adv_id",""),m=m?"&"+encodeURIComponent(this.jsonStringify(e)):"";e="";"object"===typeof d&&(e="&"+this.object_to_querystring(d));d=this._srv("/pex/"+f+"?ev="+a+"&es="+b+"&esv="+c+"&pv="+this.pv+e+m);"function"===typeof navigator.sendBeacon?navigator.sendBeacon(d):this.imgRequest(d)};
g.prototype._ctx_filter=function(){return new RegExp(atob("bWFnZW50bw"),"i")};
g.prototype._pixel_timing=function(a,b,c){function d(){p.session_time+=(new Date).getTime()-(c||0)}function e(a,b){var c=["f="+a];"undefined"!==typeof b&&c.push("ft="+b);c=p._srv("/onp/"+p._global("adroll_adv_id")+"/"+p._global("adroll_pix_id")+"?"+c.join("&"));"function"===typeof navigator.sendBeacon?navigator.sendBeacon(c):p.imgRequest(c)}function f(a,b){!b||!0!==window.__adroll_consent&&!0!==(window.__adroll_consent||{}).a||(d(),e(p.session_time,"preconsent"),"object"===typeof window.performance&&
e(p.pixelstart-window.performance.timing.domInteractive,"prepixel"))}function m(a){if("visible"===window.document.visibilityState||a.type in h)p._pixel_timing(!1,!1,l);else if("hidden"===window.document.visibilityState||a.type in k)!0===window.__adroll_consent||!0===(window.__adroll_consent||{}).a?(d(),e(p.session_time)):d()}var p=this,l=(new Date).getTime(),h=["focus","focusin","pageshow"],k=["blur","focusout","pagehide"];0===p.pixelstart&&(p.pixelstart=l);"function"===typeof window.__tcfapi&&!0===
b&&(b=!1,window.__tcfapi("addEventListener",2,f));!0!==window.__adroll_consent&&!0!==(window.__adroll_consent||{}).a?window.setTimeout(function(){p._pixel_timing(!0,b,l)},500):!0===a&&("hidden"in window.document?window.document.addEventListener("visibilitychange",m):"mozHidden"in window.document?window.document.addEventListener("mozvisibilitychange",m):"webkitHidden"in window.document?window.document.addEventListener("webkitvisibilitychange",m):"msHidden"in window.document?window.document.addEventListener("msvisibilitychange",
m):"onfocusin"in window.document?(window.document.addEventListener("focusin",m),window.document.addEventListener("focusout",m)):(window.document.addEventListener("pageshow",m),window.document.addEventListener("pagehide",m),window.document.addEventListener("focus",m),window.document.addEventListener("blur",m)))};g.prototype._gurl=function(){var a=window.location;return this.normalize_url(a.pathname+a.search)};g.prototype.get_dummy_product_for_facebook=function(a){return{product_id:"adroll_dummy_product",product_group:a,product_action:null,product_category:null}};g.prototype.facebook_dummy_product_enabled=function(){return!0};
g.prototype.extract_pid=function(a,b,c){function d(a){return a?(a=new RegExp(a,"gi"),!!a.exec(l)):null}a||(a={});var e=null,f=null,m=null,p=null,l=this._gurl(),h=this.get_external_data();h&&(f=h.product_id,e=h.product_group,m=h.product_action,p=h.adroll_product_category_id);if(!f&&a.regexp_group&&!("string"===a.regexp_group&&a.regexp_group instanceof String)&&"html"===a.regexp_group.scheme){if(d(a.blacklist_regexp)||!0!==d(a.regexp))return"";f=this.get_product_id_from_dom(a.regexp_group)}else if(!f){if(d(a.blacklist_regexp))return"";
f=this.get_product_id_from_url(l,a.regexp,a.regexp_group)}e||!a.product_group_group||"string"===a.product_group_group&&a.product_group_group instanceof String||"html"!==a.product_group_group.scheme?e||a.product_group_regexp&&(e=this.get_product_id_from_url(l,a.product_group_regexp,a.product_group_group)):e=this.get_product_id_from_dom(a.product_group_group);if(f)a={product_id:f,product_group:e,product_action:m,product_category:p};else if(this.facebook_dummy_product_enabled()&&"facebook"===b)a=this.get_dummy_product_for_facebook(e);
else return null;c&&c(a);return a};
g.prototype.get_pid=function(a){this.extract_pid(a,"adroll",function(a){if(a){var c=a.product_id,d=a.product_group,e=a.product_action,f=a.product_category;a=[];var m;if(c instanceof Array)for(m=0;m<c.length;m++)a.push(["adroll_product_id",this.normalize_var((c[m]+"").toLowerCase(),!0)]);else a.push(["adroll_product_id",this.normalize_var((c+"").toLowerCase(),!0)]);if(f instanceof Array)for(m=0;m<f.length;m++)a.push(["adroll_product_category_id",this.normalize_var((f[m]+"").toLowerCase(),!0)]);else f&&
a.push(["adroll_product_category_id",this.normalize_var((f+"").toLowerCase(),!0)]);d&&a.push(["adroll_product_group",this.normalize_var((d+"").toLowerCase(),!0)]);e&&a.push(["adroll_product_action",this.normalize_var((e+"").toLowerCase(),!0)]);(c=this.external_data_to_qs(!0))&&a.push([c]);c=this._srv(this.buildurl("/p/"+this._global("adroll_adv_id")+"/",a));d=window.document.createElement("img");d.src=c;d.height=d.width=1;d.border=0;d.setAttribute("alt","");this._head().appendChild(d)}}.bind(this))};
g.prototype.get_product_id_from_dom=function(a){var b=null,c;a.path&&(window.jQuery?(c=window.jQuery(a.path),c.length&&(c=c.eq(0),b="text"===a.attribute?c.text():c.attr(a.attribute))):window.Prototype&&window.$$?(c=window.$$(a.path),c.length&&(c=c[0],b="text"===a.attribute?c.innerText&&!window.opera?c.innerText:c.innerHTML.stripScripts().unescapeHTML().replace(/[\n\r\s]+/g," "):c.readAttribute(a.attribute))):window.YUI?(c=window.YUI().use("node"),c.one&&(c=c.one(a.path),b=null,c&&(b="text"===a.attribute?
c.get("text"):c.getAttribute(a.attribute)))):window.$$&&(c=window.$$(a.path),c.length&&(c=c[0],b="text"===a.attribute?c.get("text"):c.getProperty(a.attribute))));if(b&&(b=b.replace(/^\s\s*/,"").replace(/\s\s*$/,""),a.regular_expression&&a.regular_expression_replace))if(c=new RegExp(a.regular_expression,"gi"),b=c.exec(b),null!==b){a=a.regular_expression_replace;for(c=0;c<b.length;c++)a=a.replace(new RegExp("\\\\"+c,"gi"),b[c]||"");b=a}else b="";return b};
g.prototype.get_product_id_from_url=function(a,b,c){var d=null;try{d=parseInt(c)}catch(e){}return null!==d&&!isNaN(d)&&b&&(a=(new RegExp(b,"gi")).exec(a),null!==a&&d in a)?a[d]:null};g.prototype.render_pixel_code=function(a,b){var c=this;c._has_global("adroll_tpc")?c.render_pixel_code_exec(a,b):c.load_adroll_tpc(function(){c.render_pixel_code_exec(a,b)})};
g.prototype.render_pixel_code_exec=function(a,b){this.expire_old();var c=this._srv("/pixel"),d=window.document.createElement("script");d.setAttribute("async","true");d.type="text/javascript";var e=this.get_keywords();this.addLoadEvent(function(f){return function(){var m=[];try{200>=window.document.referrer.length&&m.push("adroll_s_ref="+window.escape(window.document.referrer))}catch(k){}try{m.push("keyw="+window.escape(e))}catch(k){}try{f._has_global("adroll_segments")&&m.push("name="+window.escape(f._global("adroll_segments").toLowerCase()))}catch(k){}try{f._has_global("adroll_p")&&
m.push("adroll_p="+window.escape(f._global("adroll_p")))}catch(k){}try{f._has_global("adroll_u")&&m.push("adroll_u="+window.escape(f._global("adroll_u")))}catch(k){}try{f._has_global("adroll_m")&&f._has_global("adroll_m_type")&&(m.push("adroll_m="+window.escape(f._global("adroll_m"))),m.push("adroll_m_type="+window.escape(f._global("adroll_m_type"))))}catch(k){}try{var p=f.get_conversion_value();p.conv_value&&m.push("conv_value="+p.conv_value);p.currency&&m.push("adroll_currency="+p.currency)}catch(k){}try{if(f._has_user_identifier()){var l=
f._global("adroll_user_identifier"),l=l.replace(/^\s\s*/,"").replace(/\s\s*$/,"");m.push("user_identifier="+window.encodeURIComponent(l))}}catch(k){}try{f._has_global("adroll_shop_id")&&(p={},f._has_global("adroll_custom_data")?p=f._global("adroll_custom_data"):f._set_global("adroll_custom_data",p),"undefined"===typeof p.adroll_shop_id&&(p.adroll_shop_id=f._global("adroll_shop_id")));var h=f.external_data_to_qs(!0);h&&m.push(h)}catch(k){}m=f.get_base_url(c,a,b,null,"",m);d.src=m;f._head().appendChild(d)}}(this));
this.addLoadEvent(function(a){return function(){var b=a._global("adroll");if(b&&"object"===typeof b){b.identify=function(){return a.identify.apply(a,arguments)};b.track=function(){return a.track.apply(a,arguments)};for(var c,d,e=0;e<b.length;e++)c=b[e][0],d=b[e][1],"identify"===c?a.identify.apply(a,d):"track"===c&&a.track.apply(a,d)}}}(this))};
g.prototype.render_ad_code=function(a,b,c,d){d=this._is_defined(d)?d:null;if(!this._is_defined(this._r[b])||d){var e=["width="+this._global("adroll_width"),"height="+this._global("adroll_height"),"x=0","y=0"];if(d){this.log("Rendering adgroup "+d);var f=this.macro_values(),m=this.macro_url_params(f,!1,!1,!1,!1);e.push(m);this.render_win_notification(f);this.render_extra_script(f);a=this.get_url(a,b,d,null,e)}else this.log("Rendering ad space "+b),a=this.get_url(a,b,null,"ad",e);this.expire_old();
a=this.maybe_apply_imp_macro(a);c&&(a=this._srv("/impression?"+e.join("&")));window.document.write('<script src="'+a+'">\x3c/script>');this._nad+=1;this._r[b]=1}};
g.prototype.render_win_notification=function(a){if(a.adroll_cpm_macro&&a.adroll_win_notif){var b=(this._secure()?"https://":"http://")+a.adroll_win_notif+a.adroll_cpm_macro;a.adroll_ad_payload&&(a.adroll_rtb_dict&&a.adroll_rtb_dict.waap||/waap=1&/.test(a.adroll_win_notif)&&!this._is_defined(a.adroll_rtb_dict))&&(b+="&ad_payload="+a.adroll_ad_payload);b=this.maybe_apply_imp_macro(b);this.imgRequest(b)}};
g.prototype.render_extra_script=function(a){a.adroll_rtb_dict&&a.adroll_rtb_dict.extra_script_src&&this.add_script_element(a.adroll_rtb_dict.extra_script_src,{})};g.prototype.add_script_element=function(a,b){var c=window.document.createElement("script"),d=this._secure()?"https://":"http://";a.match(/^(\w+:)*\/\//)&&(d="");for(var e in b)b.hasOwnProperty(e)&&"src"!==e&&c.setAttribute(e,b[e]);c.type="text/javascript";c.src=d+a;this._head().appendChild(c);return c};
g.prototype.get_base_url=function(a,b,c,d,e,f){var m=a.split("?");a=m[0]+"/"+b+"/"+c+(d?"/"+d:"")+(e?"/"+e:"");var p="?";m[1]&&(a+="?"+m[1],p="&");var m=p+"no-cookies=1&pv=",l="";this.cookieEnabled(!1)?(l=window.escape(this.get_eids()),a+=p+"pv="+this.pv+"&cookie="+l):a+=m+this.pv;f&&(a+="&"+f.join("&"));a=this.add_tpc_to_url(a);if(a.length>this._url){try{this.del(this.__adc)}catch(h){}if(a.length-l.length>this._url)return a;this.log("Url was too big, shrinking it");return this.get_url(b,c,d,e,f)}this.log("Generated url: "+
a);return a};g.prototype.get_url=function(a,b,c,d,e){var f=c?this._srv("/c"):this._srv("/r");return this.get_base_url(f,a,b,c,d,e)};g.prototype.get_eids=function(){if(this._global("adroll_ext_network")||this._global("adroll_optout"))return"";try{for(var a=this.get(this.__adc),b=a?a.split("|"):"",a=[],c=b.length-1;0<=c;c--)if(b[c]){var d=b[c].split(":");a.push([d[0],d[2]].join(":"))}return a.join("|")}catch(e){return this.del(this.__adc),""}};g.prototype.sha256=function(a){function b(a,b){return a>>>b|a<<32-b}var c=window.unescape(window.encodeURIComponent(a)),d=Math.pow(2,32),e,f="",m=[],p=8*c.length,l=[],h=[];e=0;for(var k={},n=2;64>e;n++)if(!k[n]){for(a=0;313>a;a+=n)k[a]=n;l[e]=Math.pow(n,.5)*d|0;h[e++]=Math.pow(n,1/3)*d|0}for(c+="\u0080";0!==c.length%64-56;)c+="\x00";for(a=0;a<c.length;a++){e=c.charCodeAt(a);if(e>>8)return null;m[a>>2]|=e<<(3-a)%4*8}m[m.length]=p/d|0;m[m.length]=p;for(e=0;e<m.length;){c=m.slice(e,e+=16);d=l;l=l.slice(0,
8);for(a=0;64>a;a++){var k=c[a-15],n=c[a-2],p=l[0],r=l[4],k=l[7]+(b(r,6)^b(r,11)^b(r,25))+(r&l[5]^~r&l[6])+h[a]+(c[a]=16>a?c[a]:c[a-16]+(b(k,7)^b(k,18)^k>>>3)+c[a-7]+(b(n,17)^b(n,19)^n>>>10)|0),p=(b(p,2)^b(p,13)^b(p,22))+(p&l[1]^p&l[2]^l[1]&l[2]),l=[k+p|0].concat(l);l[4]=l[4]+k|0}for(a=0;8>a;a++)l[a]=l[a]+d[a]|0}for(a=0;8>a;a++)for(e=3;e+1;e--)m=l[a]>>8*e&255,f+=(16>m?0:"")+m.toString(16);return f};g.prototype._container_is_secure=function(a){return this._is_defined(a)?a:this._secure()};g.prototype.ad_servers_url=function(a,b){return(this._container_is_secure(b)?"https://":"http://")+"d.adroll.com"+a};g.prototype.ad_request_url=function(a,b,c,d,e){var f=this._global("adroll_a_id"),m=this._global("adroll_s_id"),p=this._global("adroll_insertion_id");a=this.ad_servers_url("/r/"+m+"/"+f+"/"+p+"."+a,e);return this.format_macros(a,b,c,d)};
g.prototype.click_url=function(a,b){var c=this.ad_servers_url(a?"/click/lenient/":"/click/",!1);return this.format_macros(c,!0,!0,b)};g.prototype.engage_url=function(){var a=this.ad_servers_url("/event/",!1);return this.format_macros(a,!1,!0,!1)};g.prototype.cdn_url=function(a,b){return(this._container_is_secure(b)?"https://s.adroll.com":"http://a.adroll.com")+a};
g.prototype.ad_file_url=function(a,b){var c=this._global("adroll_ad_filename");a=a?c.split(".")[0]+a:c;c="/a/"+c.substring(0,3)+"/"+c.substring(3,6)+"/"+a;return this.cdn_url(c,b)};g.prototype.roll_crawl_url=function(){return"https://d.adroll.com/p"};g.prototype.is_lenient_click=function(a){return(a=a?this.parseUri(a):null)&&(this.endswith(a.path,".tp")||this.includes(a.path,"lenient"))};g.prototype.record_user=function(a){var b="adroll_conversion_value adroll_conversion_value_in_dollars adroll_segments adroll_email adroll_user_identifier adroll_currency".split(" "),c,d;a=a||{};var e={adroll_user_identifier:!0};for(c=0;c<b.length;c++){try{this._unset_global(b[c])}catch(f){}if(b[c]in a){b[c]in e?this._set_global(b[c],window.escape(a[b[c]])):"adroll_email"!==b[c]&&this._set_global(b[c],a[b[c]]);try{delete a[b[c]]}catch(f){}}}try{this._unset_global("adroll_custom_data")}catch(f){}for(d in a)if(a.hasOwnProperty(d)){this._set_global("adroll_custom_data",
a);break}this.render_pixel_code(this._global("adroll_adv_id"),this._global("adroll_pix_id"))};g.prototype.record_adroll_email=function(a){if(this._has_email()){var b=this._global("_adroll_email"),b=b.replace(/^\s+|\s+$/g,""),c,d,e=b.toLowerCase(),f=this.is_email_valid(b);this.is_already_hashed(e)?c=e:f&&(c=this.md5(e),d=this.sha256(e));b="/id/"+this._global("adroll_adv_id")+"/";c={hashed_email:c,sha256_email:d};f&&(e=e.split("@")[1],c.email_domain=e);a&&(c.idsource=a);b+=this._reg_lpq("?epq",c);this.imgRequest(this._srv(b))}};
g.prototype._send_plain_text_identifiers=function(a,b,c){if((a||b)&&c){c={idsource:c};var d="/id/"+this._global("adroll_adv_id")+"/";a&&(a=a.replace(/^\s+|\s+$/g,"").toLowerCase(),c.email=a,c.hashed_email=this.md5(a),c.sha256_email=this.sha256(a),a=a.split("@")[1],c.email_domain=a);b&&(c.user_identifier=b);d+=this._reg_lpq("?epq",c);this.imgRequest(this._srv(d))}};g.prototype._has_email=function(){return this._has_global("_adroll_email")};
g.prototype._has_user_identifier=function(){return this._has_global("adroll_user_identifier")&&"example_user_id"!==this._global("adroll_user_identifier")};g.prototype.is_already_hashed=function(a){return/^[a-f0-9]{32}$/.test(a)};g.prototype.is_email_valid=function(a){return/[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?/.test(a)};
g.prototype.identify=function(a,b){(a.email||a.userId)&&this._send_plain_text_identifiers(a.email,a.userId,b||"adroll-identify");a.email&&this._set_global("_adroll_email",a.email);var c=this.copyObj(a,["email","userId"]);c&&(c="/uat/"+this._global("adroll_adv_id")+"/"+this._global("adroll_pix_id")+"/?user_attributes="+window.encodeURIComponent(this.jsonStringify(c)),b&&(c+="&idsource="+b),this.imgRequest(this._srv(c)));this._queueAndCallback("identify",[a,b])};
g.prototype.track=function(a,b){this._track_pxl_assistant(a,b);if(a){var c="/uev/"+this._global("adroll_adv_id")+"/"+this._global("adroll_pix_id")+"/?event_name="+window.encodeURIComponent(a),d=this.copyObj(b);d&&(c+="&event_attributes="+window.encodeURIComponent(this.jsonStringify(d)));this.imgRequest(this._srv(c));this._queueAndCallback("track",[a,b])}};
g.prototype._reg_lpq=function(a,b){var c,d,e=[],f={},m=btoa(this.object_to_querystring(b));if(!m)return"";for(c=65;91>c;c++)e.push(String.fromCharCode(c));m=m.split("");e.push("-","_","\t");m=m.reverse();e.splice(13,0,"+","/","=");for(c=0;c<e.length-3;c++)d=e.concat(e)[c+e.length/2],f[e[c]]=d,f[e[c].toLowerCase()]=d.toLowerCase();return(e=m.map(function(a){return f[a]||a}).join("").trim())?a+"="+e:""};
g.prototype._registerCallback=function(a,b,c){this.callbacks=this.callbacks||{};this.callbackNames=this.callbackNames||[];this.callbacks[a]=this.callbacks[a]||[];if(!("function"!==typeof b||-1<this.callbackNames.indexOf(c))&&(this.callbackNames.push(c),this.callbacks[a].push(b),this.callbackQueues&&this.callbackQueues[a]&&this.callbackQueues[a].length))for(c=0;c<this.callbackQueues[a].length;c++)b.apply(null,this.callbackQueues[a][c])};
g.prototype._queueAndCallback=function(a,b){this.callbackQueues=this.callbackQueues||{};this.callbackQueues[a]=this.callbackQueues[a]||[];this.callbackQueues[a].push(b);if(this.callbacks&&this.callbacks[a]&&this.callbacks[a].length)for(var c=0;c<this.callbacks[a].length;c++)this.callbacks[a][c].apply(null,b)};g.prototype.registerIdentifyCallback=function(a,b){this._registerCallback("identify",a,b)};g.prototype.registerTrackCallback=function(a,b){this._registerCallback("track",a,b)};
g.prototype._track_pxl_assistant=function(a,b){this._has_global("__adroll_pxl_assistant_track")||this._set_global("__adroll_pxl_assistant_track",[]);this._global("__adroll_pxl_assistant_track").push({eventName:a,eventAttrs:b});if(this.__nrpa_event_handler)try{this.__nrpa_event_handler({track:this._global("__adroll_pxl_assistant_track")})}catch(c){}};g.prototype._is_defined=function(a){return"undefined"!==typeof a};g.prototype.normalize_var=function(a,b){if(!a)return"";a=a.toString().substr(0,this._kwl).replace(/,/gi,".");b&&(a=window.escape(a));return a};g.prototype.get_keywords=function(){try{var a=window.document.referrer||"";if(!a)return"";var b=this.parseUri(a);return-1!==b.host.indexOf("www.google.")?b.queryKey.q.substring(0,this._kwl):-1!==b.host.indexOf("bing.com")?b.queryKey.q.substring(0,this._kwl):""}catch(c){return""}};
g.prototype.parseUri=function(a){a=/^(?:(?![^:@]+:[^:@\/]*@)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@]*):?([^:@]*))?@)?([^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/.exec(a);for(var b={queryKey:{}},c=14,d="source protocol authority userInfo user password host port relative path directory file query anchor".split(" ");c--;)b[d[c]]=a[c]||"";b[d[12]].replace(/(?:^|&)([^&=]*)=?([^&]*)/g,function(a,c,d){c&&(b.queryKey[c]=d)});return b};
g.prototype._secure=function(){return!0};g.prototype._protocol=function(){return window.document.location.protocol};g.prototype._native=function(){try{return"http"!==this._protocol().slice(0,4)}catch(a){return!0}};g.prototype.has_param_in_url=function(a,b){var c=a.split("?");return 1<c.length&&-1!==("&"+c[1]).indexOf("&"+b+"=")};
g.prototype._srv=function(a){a=this._is_defined(a)?a:"";a=this.add_tpc_to_url("https://d.adroll.com"+a);this._has_global("__adroll_xid_ch")&&(a=this.add_param_to_url(a,"xid_ch="+(0!==this._global("__adroll_xid_ch")?"t":"f")));if(!this.has_param_in_url(a,"arrfrr")){var b=this._get_arrfrr();a=this.add_param_to_url(a,"arrfrr="+encodeURIComponent(b))}return this.add_consent_to_url(this.add_fpc_to_url(a))};
g.prototype._get_arrfrr=function(a){a||(a=window.location.href);var b=a.split("#");a=b.shift();var b=b.length?"#"+b.join("#"):null,c=a.split("?"),d=this;if(1<c.length){var e=c[1].replace(/([^&=]+)=([^&]+)/g,function(a,b,c){return b.match(/cc_number|credit_card|card_number|cv[cv]_code/)||d.is_luhn(unescape(c))?b+"=NR_REDACT":b+"="+c});c[1]!==e&&(a=c[0]+"?"+e)}b&&(a+=b);return a};
g.prototype.is_luhn=function(a){if("string"!==typeof a)return!1;a=a.replace(/\D/g,"");if(13>a.length||19<a.length)return!1;for(var b=0,c=!1,d,e=a.length-1;0<=e;e--)d=parseInt(a.charAt(e),10),c&&(d*=2,9<d&&(d-=9)),b+=d,c=!c;return 0===b%10};g.prototype._cdn=function(a){a=this._is_defined(a)?a:"";return"https://s.adroll.com"+a};g.prototype.log=function(a){this._logs.push(a)};g.prototype.read_log=function(a){return this._logs.join(a?"\n":"<br>\n")};g.prototype.normalize_url=function(a){return a.toLowerCase()};
g.prototype.imgRequest=function(a){var b=new window.Image;b.src=this.add_tpc_to_url(a);b.setAttribute("width","1");b.setAttribute("height","1");b.setAttribute("border","0");b.setAttribute("alt","");return this._head().appendChild(b)};
g.prototype.b64toint=function(a){function b(a,c){if(1>c)return"";if(c%2)return b(a,c-1)+a;var d=b(a,c/2);return d+d}var c="",d;a=a.replace("-","+").replace("_","/");for(var e=0;e<a.length;e++)d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".indexOf(a[e]).toString(2),c=c+b("0",6-d.length)+d;return parseInt(c,2)};g.prototype.copyObj=function(a,b){if(!a)return null;var c={},d=0,e;for(e in a)!a.hasOwnProperty(e)||b&&-1!==b.indexOf(e)||(d++,c[e]=a[e]);return d?c:null};
g.prototype.object_keys=function(a){if(window.Object&&window.Object.keys)return Object.keys(a);if("object"===typeof a)return[];var b=[],c;for(c in a)a.hasOwnProperty(c)&&b.push(c);return b};g.prototype.wrapException=function(a){return function(b){try{return a(b)}catch(c){}}};
g.prototype.add_tpc_to_url=function(a){var b=this._global("adroll_tpc");if(!a||!b)return a;var c=a.substr(a.indexOf("://")+3).split("/")[0];if(a.match(/[?&]adroll_tpc=/)&&"d.adroll.com"!==c)return a;0<(this._global("__adroll_xid_ch")||0)&&(b=b+"&xid_src="+(1===this._global("__adroll_xid_ch")?"cache":"srv"));return this.add_param_to_url(a,"adroll_tpc="+encodeURIComponent(b))};
g.prototype.add_fpc_to_url=function(a){var b=this.get_first_party_cookie();if(!a||!b)return a;var c=this.parseUri(a);return c.queryKey.adroll_fpc||"d.adroll.com"!==c.host&&"d.adroll.com"!==c.host+":"+c.port?a:this.add_param_to_url(a,"adroll_fpc="+encodeURIComponent(b))};
g.prototype.add_consent_to_url=function(a){if(!a)return a;if(this.has_param_in_url(a,"_arc"))return a;var b=this.get_first_party_consent();if(!b||!b.arconsent)return a;var c=a.match(/^\w+:\/\/([^\/]+)/);return c&&"d.adroll.com"!==c[1]?a:this.add_param_to_url(a,"_arc="+encodeURIComponent(b.arconsent))};
g.prototype.getSafariVersion=function(){var a=/^Mozilla\/5\.0 \([^)]+\) AppleWebKit\/[^ ]+ \(KHTML, like Gecko\) Version\/([^ ]+)( Mobile\/[^ ]+)? Safari\/[^ ]+$/i.exec(navigator.userAgent);return a?a[1]:null};g.prototype.set_tpc=function(a,b){var c=this.tpc_callback();a&&b&&this._set_global("adroll_tpc",encodeURIComponent(a)+"="+encodeURIComponent(b));c&&c.call(this)};
g.prototype.tpc_callback=function(a){var b=window.adroll_tpc_callback;window.adroll_tpc_callback=a;return a||window.adroll_xavier_called||(window.adroll_xavier_called=1,!this.call_xavier(b))?b:null};g.prototype.call_next_tpc=function(a){(a=this.tpc_callback(a))&&a.call(this)};g.prototype.extract_query_param=function(a,b){for(var c=b.split("&"),d=0;d<c.length;d++){var e=c[d].split("=");if(decodeURIComponent(e[0])===a)return decodeURIComponent(e[1])}return null};
g.prototype.get_adroll_sid=function(){var a=this.get_consent_params();return a&&(a=this.extract_query_param("_s",a))?a:this._global("adroll_sid")};g.prototype.load_adroll_tpc=function(a){this.tpc_callback(a);if(this._consent_checked)return this.set_consent();this._consent_checked=!0;this.call_consent_check()};g.prototype.get_tpc_decode_timeout=function(){return 1500};
g.prototype.set_first_party_cookie=function(){var a=this.get_first_party_cookie();a||(a=this.md5((new Date).getTime()+Math.round(1E11*Math.random())+window.navigator.userAgent.toLowerCase()+window.document.referrer)+"-"+(new Date).getTime());this.set("__adroll_fpc",a,8766)};
g.prototype.get_first_party_cookie=function(){try{var a=this.get("__adroll_fpc");if(a){var b=a.replace("-s2-","-").replace(/-$/,"");if("-"===b.charAt(32)&&b.substr(33).match(/\D/)&&Date.parse){var c=new Date(b.substr(33));if(c&&!isNaN(c.getTime()))return b.substr(0,33)+c.getTime()}return b}}catch(d){}return null};
g.prototype.call_xavier=function(a){function b(){window.RetrieveAdID&&(d=!0);if(d)if(window.RetrieveAdID){c.tpc_callback(a);var e=window.setTimeout(function(){c.set_tpc(null)},c.get_tpc_decode_timeout());window.RetrieveAdID(function(a){a&&(c._set_global("__adroll_xid_ch",1),window.clearTimeout(e),c.set_tpc("xavier",a))},function(a){c._set_global("__adroll_xid_ch",2);window.clearTimeout(e);c.set_tpc("xavier",a)})}else c._set_global("__adroll_xid_ch",0),a&&a.call(c);else window.setTimeout(function(){b()},
10)}var c=this,d=!1,e=navigator.userAgent.toLowerCase();if("US"!==this._global("__adroll_consent_user_country")||window.location.hostname.match(/(rakuten\.co\.jp|summo\.jp|goo-net\.com|dmm\.com|beforward\.jp)$/)||!(e.match(/intel mac.*? safari/)&&-1===e.indexOf("chrome")&&0<navigator.maxTouchPoints)&&(!navigator.userAgent.match(/\b(iPad|iPhone|iPod)\b/)||9>parseInt(e.substr(e.indexOf(") version/")+10),10)))return c._set_global("__adroll_xid_ch",0),!1;window.setTimeout(function(){d=!0},this.get_tpc_decode_timeout());
if(this.is_under_experiment("xid_blacklist"))return!1;this.is_under_experiment("xid_test")?this.add_script_element("https://s.dca0.com/sdk.v5.4.min.js?1621458471"):this.add_script_element("https://s.dca0.com/sdk.v5.5.min.js?1623965914");b();return!0};g.prototype.init_pixchk=function(){this.if_under_experiment_js("pixchk",function(){window.addEventListener("message",this.pixchk_handler,!1)},function(){},1E3)};
g.prototype.pixchk_handler=function(a){if(a.origin.match(/^https?:\/\/[^\/:]*\.adroll\.com\b/))try{var b=JSON.parse(a.data);"pixchk"===b.cmd&&a.source.postMessage(JSON.stringify({cmd:"pixrpl",adv_id:window.adroll_adv_id,pix_id:window.adroll_pix_id,token:b.token}),"*")}catch(c){}};
g.prototype.load_pixel_assistant=function(){if(!window.document.getElementById("adroll_nrpa_sdk")){var a=(window.location.hash||"").match("nrpa=([A-Z0-7]+)8([A-F0-9]+Z)"),b=Math.floor((new Date).getTime()/1E3)-3600;(window.sessionStorage.getItem("adroll_nrpa_sdk")||a&&a[1]===window.adroll_adv_id&&!(parseInt(a[2],16)<b))&&this.add_script_element("https://s.adroll.com/j/nrpa.js",{id:"adroll_nrpa_sdk"})}};g.prototype.set_suspended=function(){this._set_global("__adroll_data_suspended",!0)};
g.prototype.is_suspended=function(){return this._has_global("__adroll_data_suspended")};g.prototype.object_to_querystring=function(a){var b=null;if("object"===typeof a&&("function"===typeof window.URLSearchParams&&(b=(new window.URLSearchParams(a)).toString(),"[object URLSearchParams]"===b&&(b=null)),null===b)){var b="",c;for(c in a)a.hasOwnProperty(c)&&(b=b+"&"+encodeURIComponent(c)+"="+encodeURIComponent(a[c]));b=b.substr(1)}return b};window.__adroll=window.__adroll||new g;}());
(function(a){a.adroll_optout=!1;"2.0"===a.adroll_version?a.console&&a.console.debug&&a.console.debug("Both the NextRoll v1 and v2 pixel detected?"):(a.adroll_ext_network=null,a.adroll_callbacks="undefined"===typeof a.adroll_callbacks?[]:a.adroll_callbacks,a.__adroll.render_pixel_code(a.adroll_adv_id,a.adroll_pix_id))})(window);
